/**
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateLnurlAuth model module.
 * @module model/CreateLnurlAuth
 * @version 0.10.9
 */
class CreateLnurlAuth {
    /**
     * Constructs a new <code>CreateLnurlAuth</code>.
     * @alias module:model/CreateLnurlAuth
     * @param callback {String} 
     */
    constructor(callback) { 
        
        CreateLnurlAuth.initialize(this, callback);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, callback) { 
        obj['callback'] = callback;
    }

    /**
     * Constructs a <code>CreateLnurlAuth</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateLnurlAuth} obj Optional instance to populate.
     * @return {module:model/CreateLnurlAuth} The populated <code>CreateLnurlAuth</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateLnurlAuth();

            if (data.hasOwnProperty('callback')) {
                obj['callback'] = ApiClient.convertToType(data['callback'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateLnurlAuth</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateLnurlAuth</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateLnurlAuth.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['callback'] && !(typeof data['callback'] === 'string' || data['callback'] instanceof String)) {
            throw new Error("Expected the field `callback` to be a primitive type in the JSON string but got " + data['callback']);
        }

        return true;
    }


}

CreateLnurlAuth.RequiredProperties = ["callback"];

/**
 * @member {String} callback
 */
CreateLnurlAuth.prototype['callback'] = undefined;






export default CreateLnurlAuth;

