/**
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EditableSettings model module.
 * @module model/EditableSettings
 * @version 0.10.9
 */
class EditableSettings {
    /**
     * Constructs a new <code>EditableSettings</code>.
     * Base class for settings, allowing values to be overridden by environment variables.  This is useful in production for secrets you do not wish to save in code, it plays nicely with docker(-compose), Heroku and any 12 factor app design.
     * @alias module:model/EditableSettings
     */
    constructor() { 
        
        EditableSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EditableSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EditableSettings} obj Optional instance to populate.
     * @return {module:model/EditableSettings} The populated <code>EditableSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditableSettings();

            if (data.hasOwnProperty('lightning_invoice_expiry')) {
                obj['lightning_invoice_expiry'] = ApiClient.convertToType(data['lightning_invoice_expiry'], 'Number');
            }
            if (data.hasOwnProperty('boltz_network')) {
                obj['boltz_network'] = ApiClient.convertToType(data['boltz_network'], 'String');
            }
            if (data.hasOwnProperty('boltz_url')) {
                obj['boltz_url'] = ApiClient.convertToType(data['boltz_url'], 'String');
            }
            if (data.hasOwnProperty('boltz_mempool_space_url')) {
                obj['boltz_mempool_space_url'] = ApiClient.convertToType(data['boltz_mempool_space_url'], 'String');
            }
            if (data.hasOwnProperty('boltz_mempool_space_url_ws')) {
                obj['boltz_mempool_space_url_ws'] = ApiClient.convertToType(data['boltz_mempool_space_url_ws'], 'String');
            }
            if (data.hasOwnProperty('lntips_api_endpoint')) {
                obj['lntips_api_endpoint'] = ApiClient.convertToType(data['lntips_api_endpoint'], 'String');
            }
            if (data.hasOwnProperty('lntips_api_key')) {
                obj['lntips_api_key'] = ApiClient.convertToType(data['lntips_api_key'], 'String');
            }
            if (data.hasOwnProperty('lntips_admin_key')) {
                obj['lntips_admin_key'] = ApiClient.convertToType(data['lntips_admin_key'], 'String');
            }
            if (data.hasOwnProperty('lntips_invoice_key')) {
                obj['lntips_invoice_key'] = ApiClient.convertToType(data['lntips_invoice_key'], 'String');
            }
            if (data.hasOwnProperty('spark_url')) {
                obj['spark_url'] = ApiClient.convertToType(data['spark_url'], 'String');
            }
            if (data.hasOwnProperty('spark_token')) {
                obj['spark_token'] = ApiClient.convertToType(data['spark_token'], 'String');
            }
            if (data.hasOwnProperty('opennode_api_endpoint')) {
                obj['opennode_api_endpoint'] = ApiClient.convertToType(data['opennode_api_endpoint'], 'String');
            }
            if (data.hasOwnProperty('opennode_key')) {
                obj['opennode_key'] = ApiClient.convertToType(data['opennode_key'], 'String');
            }
            if (data.hasOwnProperty('opennode_admin_key')) {
                obj['opennode_admin_key'] = ApiClient.convertToType(data['opennode_admin_key'], 'String');
            }
            if (data.hasOwnProperty('opennode_invoice_key')) {
                obj['opennode_invoice_key'] = ApiClient.convertToType(data['opennode_invoice_key'], 'String');
            }
            if (data.hasOwnProperty('lnpay_api_endpoint')) {
                obj['lnpay_api_endpoint'] = ApiClient.convertToType(data['lnpay_api_endpoint'], 'String');
            }
            if (data.hasOwnProperty('lnpay_api_key')) {
                obj['lnpay_api_key'] = ApiClient.convertToType(data['lnpay_api_key'], 'String');
            }
            if (data.hasOwnProperty('lnpay_wallet_key')) {
                obj['lnpay_wallet_key'] = ApiClient.convertToType(data['lnpay_wallet_key'], 'String');
            }
            if (data.hasOwnProperty('lnpay_admin_key')) {
                obj['lnpay_admin_key'] = ApiClient.convertToType(data['lnpay_admin_key'], 'String');
            }
            if (data.hasOwnProperty('lnd_grpc_endpoint')) {
                obj['lnd_grpc_endpoint'] = ApiClient.convertToType(data['lnd_grpc_endpoint'], 'String');
            }
            if (data.hasOwnProperty('lnd_grpc_cert')) {
                obj['lnd_grpc_cert'] = ApiClient.convertToType(data['lnd_grpc_cert'], 'String');
            }
            if (data.hasOwnProperty('lnd_grpc_port')) {
                obj['lnd_grpc_port'] = ApiClient.convertToType(data['lnd_grpc_port'], 'Number');
            }
            if (data.hasOwnProperty('lnd_grpc_admin_macaroon')) {
                obj['lnd_grpc_admin_macaroon'] = ApiClient.convertToType(data['lnd_grpc_admin_macaroon'], 'String');
            }
            if (data.hasOwnProperty('lnd_grpc_invoice_macaroon')) {
                obj['lnd_grpc_invoice_macaroon'] = ApiClient.convertToType(data['lnd_grpc_invoice_macaroon'], 'String');
            }
            if (data.hasOwnProperty('lnd_grpc_macaroon')) {
                obj['lnd_grpc_macaroon'] = ApiClient.convertToType(data['lnd_grpc_macaroon'], 'String');
            }
            if (data.hasOwnProperty('lnd_grpc_macaroon_encrypted')) {
                obj['lnd_grpc_macaroon_encrypted'] = ApiClient.convertToType(data['lnd_grpc_macaroon_encrypted'], 'String');
            }
            if (data.hasOwnProperty('lnd_rest_endpoint')) {
                obj['lnd_rest_endpoint'] = ApiClient.convertToType(data['lnd_rest_endpoint'], 'String');
            }
            if (data.hasOwnProperty('lnd_rest_cert')) {
                obj['lnd_rest_cert'] = ApiClient.convertToType(data['lnd_rest_cert'], 'String');
            }
            if (data.hasOwnProperty('lnd_rest_macaroon')) {
                obj['lnd_rest_macaroon'] = ApiClient.convertToType(data['lnd_rest_macaroon'], 'String');
            }
            if (data.hasOwnProperty('lnd_rest_macaroon_encrypted')) {
                obj['lnd_rest_macaroon_encrypted'] = ApiClient.convertToType(data['lnd_rest_macaroon_encrypted'], 'String');
            }
            if (data.hasOwnProperty('lnd_cert')) {
                obj['lnd_cert'] = ApiClient.convertToType(data['lnd_cert'], 'String');
            }
            if (data.hasOwnProperty('lnd_admin_macaroon')) {
                obj['lnd_admin_macaroon'] = ApiClient.convertToType(data['lnd_admin_macaroon'], 'String');
            }
            if (data.hasOwnProperty('lnd_invoice_macaroon')) {
                obj['lnd_invoice_macaroon'] = ApiClient.convertToType(data['lnd_invoice_macaroon'], 'String');
            }
            if (data.hasOwnProperty('lnd_rest_admin_macaroon')) {
                obj['lnd_rest_admin_macaroon'] = ApiClient.convertToType(data['lnd_rest_admin_macaroon'], 'String');
            }
            if (data.hasOwnProperty('lnd_rest_invoice_macaroon')) {
                obj['lnd_rest_invoice_macaroon'] = ApiClient.convertToType(data['lnd_rest_invoice_macaroon'], 'String');
            }
            if (data.hasOwnProperty('eclair_url')) {
                obj['eclair_url'] = ApiClient.convertToType(data['eclair_url'], 'String');
            }
            if (data.hasOwnProperty('eclair_pass')) {
                obj['eclair_pass'] = ApiClient.convertToType(data['eclair_pass'], 'String');
            }
            if (data.hasOwnProperty('corelightning_rpc')) {
                obj['corelightning_rpc'] = ApiClient.convertToType(data['corelightning_rpc'], 'String');
            }
            if (data.hasOwnProperty('clightning_rpc')) {
                obj['clightning_rpc'] = ApiClient.convertToType(data['clightning_rpc'], 'String');
            }
            if (data.hasOwnProperty('cliche_endpoint')) {
                obj['cliche_endpoint'] = ApiClient.convertToType(data['cliche_endpoint'], 'String');
            }
            if (data.hasOwnProperty('lnbits_endpoint')) {
                obj['lnbits_endpoint'] = ApiClient.convertToType(data['lnbits_endpoint'], 'String');
            }
            if (data.hasOwnProperty('lnbits_key')) {
                obj['lnbits_key'] = ApiClient.convertToType(data['lnbits_key'], 'String');
            }
            if (data.hasOwnProperty('lnbits_admin_key')) {
                obj['lnbits_admin_key'] = ApiClient.convertToType(data['lnbits_admin_key'], 'String');
            }
            if (data.hasOwnProperty('lnbits_invoice_key')) {
                obj['lnbits_invoice_key'] = ApiClient.convertToType(data['lnbits_invoice_key'], 'String');
            }
            if (data.hasOwnProperty('fake_wallet_secret')) {
                obj['fake_wallet_secret'] = ApiClient.convertToType(data['fake_wallet_secret'], 'String');
            }
            if (data.hasOwnProperty('lnbits_backend_wallet_class')) {
                obj['lnbits_backend_wallet_class'] = ApiClient.convertToType(data['lnbits_backend_wallet_class'], 'String');
            }
            if (data.hasOwnProperty('lnbits_rate_limit_no')) {
                obj['lnbits_rate_limit_no'] = ApiClient.convertToType(data['lnbits_rate_limit_no'], 'String');
            }
            if (data.hasOwnProperty('lnbits_rate_limit_unit')) {
                obj['lnbits_rate_limit_unit'] = ApiClient.convertToType(data['lnbits_rate_limit_unit'], 'String');
            }
            if (data.hasOwnProperty('lnbits_allowed_ips')) {
                obj['lnbits_allowed_ips'] = ApiClient.convertToType(data['lnbits_allowed_ips'], ['String']);
            }
            if (data.hasOwnProperty('lnbits_blocked_ips')) {
                obj['lnbits_blocked_ips'] = ApiClient.convertToType(data['lnbits_blocked_ips'], ['String']);
            }
            if (data.hasOwnProperty('lnbits_notifications')) {
                obj['lnbits_notifications'] = ApiClient.convertToType(data['lnbits_notifications'], 'Boolean');
            }
            if (data.hasOwnProperty('lnbits_killswitch')) {
                obj['lnbits_killswitch'] = ApiClient.convertToType(data['lnbits_killswitch'], 'Boolean');
            }
            if (data.hasOwnProperty('lnbits_killswitch_interval')) {
                obj['lnbits_killswitch_interval'] = ApiClient.convertToType(data['lnbits_killswitch_interval'], 'Number');
            }
            if (data.hasOwnProperty('lnbits_watchdog')) {
                obj['lnbits_watchdog'] = ApiClient.convertToType(data['lnbits_watchdog'], 'Boolean');
            }
            if (data.hasOwnProperty('lnbits_watchdog_interval')) {
                obj['lnbits_watchdog_interval'] = ApiClient.convertToType(data['lnbits_watchdog_interval'], 'Number');
            }
            if (data.hasOwnProperty('lnbits_watchdog_delta')) {
                obj['lnbits_watchdog_delta'] = ApiClient.convertToType(data['lnbits_watchdog_delta'], 'Number');
            }
            if (data.hasOwnProperty('lnbits_status_manifest')) {
                obj['lnbits_status_manifest'] = ApiClient.convertToType(data['lnbits_status_manifest'], 'String');
            }
            if (data.hasOwnProperty('lnbits_baseurl')) {
                obj['lnbits_baseurl'] = ApiClient.convertToType(data['lnbits_baseurl'], 'String');
            }
            if (data.hasOwnProperty('lnbits_reserve_fee_min')) {
                obj['lnbits_reserve_fee_min'] = ApiClient.convertToType(data['lnbits_reserve_fee_min'], 'Number');
            }
            if (data.hasOwnProperty('lnbits_reserve_fee_percent')) {
                obj['lnbits_reserve_fee_percent'] = ApiClient.convertToType(data['lnbits_reserve_fee_percent'], 'Number');
            }
            if (data.hasOwnProperty('lnbits_service_fee')) {
                obj['lnbits_service_fee'] = ApiClient.convertToType(data['lnbits_service_fee'], 'Number');
            }
            if (data.hasOwnProperty('lnbits_hide_api')) {
                obj['lnbits_hide_api'] = ApiClient.convertToType(data['lnbits_hide_api'], 'Boolean');
            }
            if (data.hasOwnProperty('lnbits_denomination')) {
                obj['lnbits_denomination'] = ApiClient.convertToType(data['lnbits_denomination'], 'String');
            }
            if (data.hasOwnProperty('lnbits_site_title')) {
                obj['lnbits_site_title'] = ApiClient.convertToType(data['lnbits_site_title'], 'String');
            }
            if (data.hasOwnProperty('lnbits_site_tagline')) {
                obj['lnbits_site_tagline'] = ApiClient.convertToType(data['lnbits_site_tagline'], 'String');
            }
            if (data.hasOwnProperty('lnbits_site_description')) {
                obj['lnbits_site_description'] = ApiClient.convertToType(data['lnbits_site_description'], 'String');
            }
            if (data.hasOwnProperty('lnbits_default_wallet_name')) {
                obj['lnbits_default_wallet_name'] = ApiClient.convertToType(data['lnbits_default_wallet_name'], 'String');
            }
            if (data.hasOwnProperty('lnbits_theme_options')) {
                obj['lnbits_theme_options'] = ApiClient.convertToType(data['lnbits_theme_options'], ['String']);
            }
            if (data.hasOwnProperty('lnbits_custom_logo')) {
                obj['lnbits_custom_logo'] = ApiClient.convertToType(data['lnbits_custom_logo'], 'String');
            }
            if (data.hasOwnProperty('lnbits_ad_space_title')) {
                obj['lnbits_ad_space_title'] = ApiClient.convertToType(data['lnbits_ad_space_title'], 'String');
            }
            if (data.hasOwnProperty('lnbits_ad_space')) {
                obj['lnbits_ad_space'] = ApiClient.convertToType(data['lnbits_ad_space'], 'String');
            }
            if (data.hasOwnProperty('lnbits_ad_space_enabled')) {
                obj['lnbits_ad_space_enabled'] = ApiClient.convertToType(data['lnbits_ad_space_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('lnbits_allowed_currencies')) {
                obj['lnbits_allowed_currencies'] = ApiClient.convertToType(data['lnbits_allowed_currencies'], ['String']);
            }
            if (data.hasOwnProperty('lnbits_admin_extensions')) {
                obj['lnbits_admin_extensions'] = ApiClient.convertToType(data['lnbits_admin_extensions'], ['String']);
            }
            if (data.hasOwnProperty('lnbits_extensions_manifests')) {
                obj['lnbits_extensions_manifests'] = ApiClient.convertToType(data['lnbits_extensions_manifests'], ['String']);
            }
            if (data.hasOwnProperty('lnbits_admin_users')) {
                obj['lnbits_admin_users'] = ApiClient.convertToType(data['lnbits_admin_users'], ['String']);
            }
            if (data.hasOwnProperty('lnbits_allowed_users')) {
                obj['lnbits_allowed_users'] = ApiClient.convertToType(data['lnbits_allowed_users'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EditableSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EditableSettings</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['boltz_network'] && !(typeof data['boltz_network'] === 'string' || data['boltz_network'] instanceof String)) {
            throw new Error("Expected the field `boltz_network` to be a primitive type in the JSON string but got " + data['boltz_network']);
        }
        // ensure the json data is a string
        if (data['boltz_url'] && !(typeof data['boltz_url'] === 'string' || data['boltz_url'] instanceof String)) {
            throw new Error("Expected the field `boltz_url` to be a primitive type in the JSON string but got " + data['boltz_url']);
        }
        // ensure the json data is a string
        if (data['boltz_mempool_space_url'] && !(typeof data['boltz_mempool_space_url'] === 'string' || data['boltz_mempool_space_url'] instanceof String)) {
            throw new Error("Expected the field `boltz_mempool_space_url` to be a primitive type in the JSON string but got " + data['boltz_mempool_space_url']);
        }
        // ensure the json data is a string
        if (data['boltz_mempool_space_url_ws'] && !(typeof data['boltz_mempool_space_url_ws'] === 'string' || data['boltz_mempool_space_url_ws'] instanceof String)) {
            throw new Error("Expected the field `boltz_mempool_space_url_ws` to be a primitive type in the JSON string but got " + data['boltz_mempool_space_url_ws']);
        }
        // ensure the json data is a string
        if (data['lntips_api_endpoint'] && !(typeof data['lntips_api_endpoint'] === 'string' || data['lntips_api_endpoint'] instanceof String)) {
            throw new Error("Expected the field `lntips_api_endpoint` to be a primitive type in the JSON string but got " + data['lntips_api_endpoint']);
        }
        // ensure the json data is a string
        if (data['lntips_api_key'] && !(typeof data['lntips_api_key'] === 'string' || data['lntips_api_key'] instanceof String)) {
            throw new Error("Expected the field `lntips_api_key` to be a primitive type in the JSON string but got " + data['lntips_api_key']);
        }
        // ensure the json data is a string
        if (data['lntips_admin_key'] && !(typeof data['lntips_admin_key'] === 'string' || data['lntips_admin_key'] instanceof String)) {
            throw new Error("Expected the field `lntips_admin_key` to be a primitive type in the JSON string but got " + data['lntips_admin_key']);
        }
        // ensure the json data is a string
        if (data['lntips_invoice_key'] && !(typeof data['lntips_invoice_key'] === 'string' || data['lntips_invoice_key'] instanceof String)) {
            throw new Error("Expected the field `lntips_invoice_key` to be a primitive type in the JSON string but got " + data['lntips_invoice_key']);
        }
        // ensure the json data is a string
        if (data['spark_url'] && !(typeof data['spark_url'] === 'string' || data['spark_url'] instanceof String)) {
            throw new Error("Expected the field `spark_url` to be a primitive type in the JSON string but got " + data['spark_url']);
        }
        // ensure the json data is a string
        if (data['spark_token'] && !(typeof data['spark_token'] === 'string' || data['spark_token'] instanceof String)) {
            throw new Error("Expected the field `spark_token` to be a primitive type in the JSON string but got " + data['spark_token']);
        }
        // ensure the json data is a string
        if (data['opennode_api_endpoint'] && !(typeof data['opennode_api_endpoint'] === 'string' || data['opennode_api_endpoint'] instanceof String)) {
            throw new Error("Expected the field `opennode_api_endpoint` to be a primitive type in the JSON string but got " + data['opennode_api_endpoint']);
        }
        // ensure the json data is a string
        if (data['opennode_key'] && !(typeof data['opennode_key'] === 'string' || data['opennode_key'] instanceof String)) {
            throw new Error("Expected the field `opennode_key` to be a primitive type in the JSON string but got " + data['opennode_key']);
        }
        // ensure the json data is a string
        if (data['opennode_admin_key'] && !(typeof data['opennode_admin_key'] === 'string' || data['opennode_admin_key'] instanceof String)) {
            throw new Error("Expected the field `opennode_admin_key` to be a primitive type in the JSON string but got " + data['opennode_admin_key']);
        }
        // ensure the json data is a string
        if (data['opennode_invoice_key'] && !(typeof data['opennode_invoice_key'] === 'string' || data['opennode_invoice_key'] instanceof String)) {
            throw new Error("Expected the field `opennode_invoice_key` to be a primitive type in the JSON string but got " + data['opennode_invoice_key']);
        }
        // ensure the json data is a string
        if (data['lnpay_api_endpoint'] && !(typeof data['lnpay_api_endpoint'] === 'string' || data['lnpay_api_endpoint'] instanceof String)) {
            throw new Error("Expected the field `lnpay_api_endpoint` to be a primitive type in the JSON string but got " + data['lnpay_api_endpoint']);
        }
        // ensure the json data is a string
        if (data['lnpay_api_key'] && !(typeof data['lnpay_api_key'] === 'string' || data['lnpay_api_key'] instanceof String)) {
            throw new Error("Expected the field `lnpay_api_key` to be a primitive type in the JSON string but got " + data['lnpay_api_key']);
        }
        // ensure the json data is a string
        if (data['lnpay_wallet_key'] && !(typeof data['lnpay_wallet_key'] === 'string' || data['lnpay_wallet_key'] instanceof String)) {
            throw new Error("Expected the field `lnpay_wallet_key` to be a primitive type in the JSON string but got " + data['lnpay_wallet_key']);
        }
        // ensure the json data is a string
        if (data['lnpay_admin_key'] && !(typeof data['lnpay_admin_key'] === 'string' || data['lnpay_admin_key'] instanceof String)) {
            throw new Error("Expected the field `lnpay_admin_key` to be a primitive type in the JSON string but got " + data['lnpay_admin_key']);
        }
        // ensure the json data is a string
        if (data['lnd_grpc_endpoint'] && !(typeof data['lnd_grpc_endpoint'] === 'string' || data['lnd_grpc_endpoint'] instanceof String)) {
            throw new Error("Expected the field `lnd_grpc_endpoint` to be a primitive type in the JSON string but got " + data['lnd_grpc_endpoint']);
        }
        // ensure the json data is a string
        if (data['lnd_grpc_cert'] && !(typeof data['lnd_grpc_cert'] === 'string' || data['lnd_grpc_cert'] instanceof String)) {
            throw new Error("Expected the field `lnd_grpc_cert` to be a primitive type in the JSON string but got " + data['lnd_grpc_cert']);
        }
        // ensure the json data is a string
        if (data['lnd_grpc_admin_macaroon'] && !(typeof data['lnd_grpc_admin_macaroon'] === 'string' || data['lnd_grpc_admin_macaroon'] instanceof String)) {
            throw new Error("Expected the field `lnd_grpc_admin_macaroon` to be a primitive type in the JSON string but got " + data['lnd_grpc_admin_macaroon']);
        }
        // ensure the json data is a string
        if (data['lnd_grpc_invoice_macaroon'] && !(typeof data['lnd_grpc_invoice_macaroon'] === 'string' || data['lnd_grpc_invoice_macaroon'] instanceof String)) {
            throw new Error("Expected the field `lnd_grpc_invoice_macaroon` to be a primitive type in the JSON string but got " + data['lnd_grpc_invoice_macaroon']);
        }
        // ensure the json data is a string
        if (data['lnd_grpc_macaroon'] && !(typeof data['lnd_grpc_macaroon'] === 'string' || data['lnd_grpc_macaroon'] instanceof String)) {
            throw new Error("Expected the field `lnd_grpc_macaroon` to be a primitive type in the JSON string but got " + data['lnd_grpc_macaroon']);
        }
        // ensure the json data is a string
        if (data['lnd_grpc_macaroon_encrypted'] && !(typeof data['lnd_grpc_macaroon_encrypted'] === 'string' || data['lnd_grpc_macaroon_encrypted'] instanceof String)) {
            throw new Error("Expected the field `lnd_grpc_macaroon_encrypted` to be a primitive type in the JSON string but got " + data['lnd_grpc_macaroon_encrypted']);
        }
        // ensure the json data is a string
        if (data['lnd_rest_endpoint'] && !(typeof data['lnd_rest_endpoint'] === 'string' || data['lnd_rest_endpoint'] instanceof String)) {
            throw new Error("Expected the field `lnd_rest_endpoint` to be a primitive type in the JSON string but got " + data['lnd_rest_endpoint']);
        }
        // ensure the json data is a string
        if (data['lnd_rest_cert'] && !(typeof data['lnd_rest_cert'] === 'string' || data['lnd_rest_cert'] instanceof String)) {
            throw new Error("Expected the field `lnd_rest_cert` to be a primitive type in the JSON string but got " + data['lnd_rest_cert']);
        }
        // ensure the json data is a string
        if (data['lnd_rest_macaroon'] && !(typeof data['lnd_rest_macaroon'] === 'string' || data['lnd_rest_macaroon'] instanceof String)) {
            throw new Error("Expected the field `lnd_rest_macaroon` to be a primitive type in the JSON string but got " + data['lnd_rest_macaroon']);
        }
        // ensure the json data is a string
        if (data['lnd_rest_macaroon_encrypted'] && !(typeof data['lnd_rest_macaroon_encrypted'] === 'string' || data['lnd_rest_macaroon_encrypted'] instanceof String)) {
            throw new Error("Expected the field `lnd_rest_macaroon_encrypted` to be a primitive type in the JSON string but got " + data['lnd_rest_macaroon_encrypted']);
        }
        // ensure the json data is a string
        if (data['lnd_cert'] && !(typeof data['lnd_cert'] === 'string' || data['lnd_cert'] instanceof String)) {
            throw new Error("Expected the field `lnd_cert` to be a primitive type in the JSON string but got " + data['lnd_cert']);
        }
        // ensure the json data is a string
        if (data['lnd_admin_macaroon'] && !(typeof data['lnd_admin_macaroon'] === 'string' || data['lnd_admin_macaroon'] instanceof String)) {
            throw new Error("Expected the field `lnd_admin_macaroon` to be a primitive type in the JSON string but got " + data['lnd_admin_macaroon']);
        }
        // ensure the json data is a string
        if (data['lnd_invoice_macaroon'] && !(typeof data['lnd_invoice_macaroon'] === 'string' || data['lnd_invoice_macaroon'] instanceof String)) {
            throw new Error("Expected the field `lnd_invoice_macaroon` to be a primitive type in the JSON string but got " + data['lnd_invoice_macaroon']);
        }
        // ensure the json data is a string
        if (data['lnd_rest_admin_macaroon'] && !(typeof data['lnd_rest_admin_macaroon'] === 'string' || data['lnd_rest_admin_macaroon'] instanceof String)) {
            throw new Error("Expected the field `lnd_rest_admin_macaroon` to be a primitive type in the JSON string but got " + data['lnd_rest_admin_macaroon']);
        }
        // ensure the json data is a string
        if (data['lnd_rest_invoice_macaroon'] && !(typeof data['lnd_rest_invoice_macaroon'] === 'string' || data['lnd_rest_invoice_macaroon'] instanceof String)) {
            throw new Error("Expected the field `lnd_rest_invoice_macaroon` to be a primitive type in the JSON string but got " + data['lnd_rest_invoice_macaroon']);
        }
        // ensure the json data is a string
        if (data['eclair_url'] && !(typeof data['eclair_url'] === 'string' || data['eclair_url'] instanceof String)) {
            throw new Error("Expected the field `eclair_url` to be a primitive type in the JSON string but got " + data['eclair_url']);
        }
        // ensure the json data is a string
        if (data['eclair_pass'] && !(typeof data['eclair_pass'] === 'string' || data['eclair_pass'] instanceof String)) {
            throw new Error("Expected the field `eclair_pass` to be a primitive type in the JSON string but got " + data['eclair_pass']);
        }
        // ensure the json data is a string
        if (data['corelightning_rpc'] && !(typeof data['corelightning_rpc'] === 'string' || data['corelightning_rpc'] instanceof String)) {
            throw new Error("Expected the field `corelightning_rpc` to be a primitive type in the JSON string but got " + data['corelightning_rpc']);
        }
        // ensure the json data is a string
        if (data['clightning_rpc'] && !(typeof data['clightning_rpc'] === 'string' || data['clightning_rpc'] instanceof String)) {
            throw new Error("Expected the field `clightning_rpc` to be a primitive type in the JSON string but got " + data['clightning_rpc']);
        }
        // ensure the json data is a string
        if (data['cliche_endpoint'] && !(typeof data['cliche_endpoint'] === 'string' || data['cliche_endpoint'] instanceof String)) {
            throw new Error("Expected the field `cliche_endpoint` to be a primitive type in the JSON string but got " + data['cliche_endpoint']);
        }
        // ensure the json data is a string
        if (data['lnbits_endpoint'] && !(typeof data['lnbits_endpoint'] === 'string' || data['lnbits_endpoint'] instanceof String)) {
            throw new Error("Expected the field `lnbits_endpoint` to be a primitive type in the JSON string but got " + data['lnbits_endpoint']);
        }
        // ensure the json data is a string
        if (data['lnbits_key'] && !(typeof data['lnbits_key'] === 'string' || data['lnbits_key'] instanceof String)) {
            throw new Error("Expected the field `lnbits_key` to be a primitive type in the JSON string but got " + data['lnbits_key']);
        }
        // ensure the json data is a string
        if (data['lnbits_admin_key'] && !(typeof data['lnbits_admin_key'] === 'string' || data['lnbits_admin_key'] instanceof String)) {
            throw new Error("Expected the field `lnbits_admin_key` to be a primitive type in the JSON string but got " + data['lnbits_admin_key']);
        }
        // ensure the json data is a string
        if (data['lnbits_invoice_key'] && !(typeof data['lnbits_invoice_key'] === 'string' || data['lnbits_invoice_key'] instanceof String)) {
            throw new Error("Expected the field `lnbits_invoice_key` to be a primitive type in the JSON string but got " + data['lnbits_invoice_key']);
        }
        // ensure the json data is a string
        if (data['fake_wallet_secret'] && !(typeof data['fake_wallet_secret'] === 'string' || data['fake_wallet_secret'] instanceof String)) {
            throw new Error("Expected the field `fake_wallet_secret` to be a primitive type in the JSON string but got " + data['fake_wallet_secret']);
        }
        // ensure the json data is a string
        if (data['lnbits_backend_wallet_class'] && !(typeof data['lnbits_backend_wallet_class'] === 'string' || data['lnbits_backend_wallet_class'] instanceof String)) {
            throw new Error("Expected the field `lnbits_backend_wallet_class` to be a primitive type in the JSON string but got " + data['lnbits_backend_wallet_class']);
        }
        // ensure the json data is a string
        if (data['lnbits_rate_limit_no'] && !(typeof data['lnbits_rate_limit_no'] === 'string' || data['lnbits_rate_limit_no'] instanceof String)) {
            throw new Error("Expected the field `lnbits_rate_limit_no` to be a primitive type in the JSON string but got " + data['lnbits_rate_limit_no']);
        }
        // ensure the json data is a string
        if (data['lnbits_rate_limit_unit'] && !(typeof data['lnbits_rate_limit_unit'] === 'string' || data['lnbits_rate_limit_unit'] instanceof String)) {
            throw new Error("Expected the field `lnbits_rate_limit_unit` to be a primitive type in the JSON string but got " + data['lnbits_rate_limit_unit']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lnbits_allowed_ips'])) {
            throw new Error("Expected the field `lnbits_allowed_ips` to be an array in the JSON data but got " + data['lnbits_allowed_ips']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lnbits_blocked_ips'])) {
            throw new Error("Expected the field `lnbits_blocked_ips` to be an array in the JSON data but got " + data['lnbits_blocked_ips']);
        }
        // ensure the json data is a string
        if (data['lnbits_status_manifest'] && !(typeof data['lnbits_status_manifest'] === 'string' || data['lnbits_status_manifest'] instanceof String)) {
            throw new Error("Expected the field `lnbits_status_manifest` to be a primitive type in the JSON string but got " + data['lnbits_status_manifest']);
        }
        // ensure the json data is a string
        if (data['lnbits_baseurl'] && !(typeof data['lnbits_baseurl'] === 'string' || data['lnbits_baseurl'] instanceof String)) {
            throw new Error("Expected the field `lnbits_baseurl` to be a primitive type in the JSON string but got " + data['lnbits_baseurl']);
        }
        // ensure the json data is a string
        if (data['lnbits_denomination'] && !(typeof data['lnbits_denomination'] === 'string' || data['lnbits_denomination'] instanceof String)) {
            throw new Error("Expected the field `lnbits_denomination` to be a primitive type in the JSON string but got " + data['lnbits_denomination']);
        }
        // ensure the json data is a string
        if (data['lnbits_site_title'] && !(typeof data['lnbits_site_title'] === 'string' || data['lnbits_site_title'] instanceof String)) {
            throw new Error("Expected the field `lnbits_site_title` to be a primitive type in the JSON string but got " + data['lnbits_site_title']);
        }
        // ensure the json data is a string
        if (data['lnbits_site_tagline'] && !(typeof data['lnbits_site_tagline'] === 'string' || data['lnbits_site_tagline'] instanceof String)) {
            throw new Error("Expected the field `lnbits_site_tagline` to be a primitive type in the JSON string but got " + data['lnbits_site_tagline']);
        }
        // ensure the json data is a string
        if (data['lnbits_site_description'] && !(typeof data['lnbits_site_description'] === 'string' || data['lnbits_site_description'] instanceof String)) {
            throw new Error("Expected the field `lnbits_site_description` to be a primitive type in the JSON string but got " + data['lnbits_site_description']);
        }
        // ensure the json data is a string
        if (data['lnbits_default_wallet_name'] && !(typeof data['lnbits_default_wallet_name'] === 'string' || data['lnbits_default_wallet_name'] instanceof String)) {
            throw new Error("Expected the field `lnbits_default_wallet_name` to be a primitive type in the JSON string but got " + data['lnbits_default_wallet_name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lnbits_theme_options'])) {
            throw new Error("Expected the field `lnbits_theme_options` to be an array in the JSON data but got " + data['lnbits_theme_options']);
        }
        // ensure the json data is a string
        if (data['lnbits_custom_logo'] && !(typeof data['lnbits_custom_logo'] === 'string' || data['lnbits_custom_logo'] instanceof String)) {
            throw new Error("Expected the field `lnbits_custom_logo` to be a primitive type in the JSON string but got " + data['lnbits_custom_logo']);
        }
        // ensure the json data is a string
        if (data['lnbits_ad_space_title'] && !(typeof data['lnbits_ad_space_title'] === 'string' || data['lnbits_ad_space_title'] instanceof String)) {
            throw new Error("Expected the field `lnbits_ad_space_title` to be a primitive type in the JSON string but got " + data['lnbits_ad_space_title']);
        }
        // ensure the json data is a string
        if (data['lnbits_ad_space'] && !(typeof data['lnbits_ad_space'] === 'string' || data['lnbits_ad_space'] instanceof String)) {
            throw new Error("Expected the field `lnbits_ad_space` to be a primitive type in the JSON string but got " + data['lnbits_ad_space']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lnbits_allowed_currencies'])) {
            throw new Error("Expected the field `lnbits_allowed_currencies` to be an array in the JSON data but got " + data['lnbits_allowed_currencies']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lnbits_admin_extensions'])) {
            throw new Error("Expected the field `lnbits_admin_extensions` to be an array in the JSON data but got " + data['lnbits_admin_extensions']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lnbits_extensions_manifests'])) {
            throw new Error("Expected the field `lnbits_extensions_manifests` to be an array in the JSON data but got " + data['lnbits_extensions_manifests']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lnbits_admin_users'])) {
            throw new Error("Expected the field `lnbits_admin_users` to be an array in the JSON data but got " + data['lnbits_admin_users']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lnbits_allowed_users'])) {
            throw new Error("Expected the field `lnbits_allowed_users` to be an array in the JSON data but got " + data['lnbits_allowed_users']);
        }

        return true;
    }


}



/**
 * @member {Number} lightning_invoice_expiry
 * @default 600
 */
EditableSettings.prototype['lightning_invoice_expiry'] = 600;

/**
 * @member {String} boltz_network
 * @default 'main'
 */
EditableSettings.prototype['boltz_network'] = 'main';

/**
 * @member {String} boltz_url
 * @default 'https://boltz.exchange/api'
 */
EditableSettings.prototype['boltz_url'] = 'https://boltz.exchange/api';

/**
 * @member {String} boltz_mempool_space_url
 * @default 'https://mempool.space'
 */
EditableSettings.prototype['boltz_mempool_space_url'] = 'https://mempool.space';

/**
 * @member {String} boltz_mempool_space_url_ws
 * @default 'wss://mempool.space'
 */
EditableSettings.prototype['boltz_mempool_space_url_ws'] = 'wss://mempool.space';

/**
 * @member {String} lntips_api_endpoint
 */
EditableSettings.prototype['lntips_api_endpoint'] = undefined;

/**
 * @member {String} lntips_api_key
 */
EditableSettings.prototype['lntips_api_key'] = undefined;

/**
 * @member {String} lntips_admin_key
 */
EditableSettings.prototype['lntips_admin_key'] = undefined;

/**
 * @member {String} lntips_invoice_key
 */
EditableSettings.prototype['lntips_invoice_key'] = undefined;

/**
 * @member {String} spark_url
 */
EditableSettings.prototype['spark_url'] = undefined;

/**
 * @member {String} spark_token
 */
EditableSettings.prototype['spark_token'] = undefined;

/**
 * @member {String} opennode_api_endpoint
 */
EditableSettings.prototype['opennode_api_endpoint'] = undefined;

/**
 * @member {String} opennode_key
 */
EditableSettings.prototype['opennode_key'] = undefined;

/**
 * @member {String} opennode_admin_key
 */
EditableSettings.prototype['opennode_admin_key'] = undefined;

/**
 * @member {String} opennode_invoice_key
 */
EditableSettings.prototype['opennode_invoice_key'] = undefined;

/**
 * @member {String} lnpay_api_endpoint
 */
EditableSettings.prototype['lnpay_api_endpoint'] = undefined;

/**
 * @member {String} lnpay_api_key
 */
EditableSettings.prototype['lnpay_api_key'] = undefined;

/**
 * @member {String} lnpay_wallet_key
 */
EditableSettings.prototype['lnpay_wallet_key'] = undefined;

/**
 * @member {String} lnpay_admin_key
 */
EditableSettings.prototype['lnpay_admin_key'] = undefined;

/**
 * @member {String} lnd_grpc_endpoint
 */
EditableSettings.prototype['lnd_grpc_endpoint'] = undefined;

/**
 * @member {String} lnd_grpc_cert
 */
EditableSettings.prototype['lnd_grpc_cert'] = undefined;

/**
 * @member {Number} lnd_grpc_port
 */
EditableSettings.prototype['lnd_grpc_port'] = undefined;

/**
 * @member {String} lnd_grpc_admin_macaroon
 */
EditableSettings.prototype['lnd_grpc_admin_macaroon'] = undefined;

/**
 * @member {String} lnd_grpc_invoice_macaroon
 */
EditableSettings.prototype['lnd_grpc_invoice_macaroon'] = undefined;

/**
 * @member {String} lnd_grpc_macaroon
 */
EditableSettings.prototype['lnd_grpc_macaroon'] = undefined;

/**
 * @member {String} lnd_grpc_macaroon_encrypted
 */
EditableSettings.prototype['lnd_grpc_macaroon_encrypted'] = undefined;

/**
 * @member {String} lnd_rest_endpoint
 */
EditableSettings.prototype['lnd_rest_endpoint'] = undefined;

/**
 * @member {String} lnd_rest_cert
 */
EditableSettings.prototype['lnd_rest_cert'] = undefined;

/**
 * @member {String} lnd_rest_macaroon
 */
EditableSettings.prototype['lnd_rest_macaroon'] = undefined;

/**
 * @member {String} lnd_rest_macaroon_encrypted
 */
EditableSettings.prototype['lnd_rest_macaroon_encrypted'] = undefined;

/**
 * @member {String} lnd_cert
 */
EditableSettings.prototype['lnd_cert'] = undefined;

/**
 * @member {String} lnd_admin_macaroon
 */
EditableSettings.prototype['lnd_admin_macaroon'] = undefined;

/**
 * @member {String} lnd_invoice_macaroon
 */
EditableSettings.prototype['lnd_invoice_macaroon'] = undefined;

/**
 * @member {String} lnd_rest_admin_macaroon
 */
EditableSettings.prototype['lnd_rest_admin_macaroon'] = undefined;

/**
 * @member {String} lnd_rest_invoice_macaroon
 */
EditableSettings.prototype['lnd_rest_invoice_macaroon'] = undefined;

/**
 * @member {String} eclair_url
 */
EditableSettings.prototype['eclair_url'] = undefined;

/**
 * @member {String} eclair_pass
 */
EditableSettings.prototype['eclair_pass'] = undefined;

/**
 * @member {String} corelightning_rpc
 */
EditableSettings.prototype['corelightning_rpc'] = undefined;

/**
 * @member {String} clightning_rpc
 */
EditableSettings.prototype['clightning_rpc'] = undefined;

/**
 * @member {String} cliche_endpoint
 */
EditableSettings.prototype['cliche_endpoint'] = undefined;

/**
 * @member {String} lnbits_endpoint
 * @default 'https://legend.lnbits.com'
 */
EditableSettings.prototype['lnbits_endpoint'] = 'https://legend.lnbits.com';

/**
 * @member {String} lnbits_key
 */
EditableSettings.prototype['lnbits_key'] = undefined;

/**
 * @member {String} lnbits_admin_key
 */
EditableSettings.prototype['lnbits_admin_key'] = undefined;

/**
 * @member {String} lnbits_invoice_key
 */
EditableSettings.prototype['lnbits_invoice_key'] = undefined;

/**
 * @member {String} fake_wallet_secret
 * @default 'ToTheMoon1'
 */
EditableSettings.prototype['fake_wallet_secret'] = 'ToTheMoon1';

/**
 * @member {String} lnbits_backend_wallet_class
 * @default 'VoidWallet'
 */
EditableSettings.prototype['lnbits_backend_wallet_class'] = 'VoidWallet';

/**
 * @member {String} lnbits_rate_limit_no
 * @default '200'
 */
EditableSettings.prototype['lnbits_rate_limit_no'] = '200';

/**
 * @member {String} lnbits_rate_limit_unit
 * @default 'minute'
 */
EditableSettings.prototype['lnbits_rate_limit_unit'] = 'minute';

/**
 * @member {Array.<String>} lnbits_allowed_ips
 */
EditableSettings.prototype['lnbits_allowed_ips'] = undefined;

/**
 * @member {Array.<String>} lnbits_blocked_ips
 */
EditableSettings.prototype['lnbits_blocked_ips'] = undefined;

/**
 * @member {Boolean} lnbits_notifications
 * @default false
 */
EditableSettings.prototype['lnbits_notifications'] = false;

/**
 * @member {Boolean} lnbits_killswitch
 * @default false
 */
EditableSettings.prototype['lnbits_killswitch'] = false;

/**
 * @member {Number} lnbits_killswitch_interval
 * @default 60
 */
EditableSettings.prototype['lnbits_killswitch_interval'] = 60;

/**
 * @member {Boolean} lnbits_watchdog
 * @default false
 */
EditableSettings.prototype['lnbits_watchdog'] = false;

/**
 * @member {Number} lnbits_watchdog_interval
 * @default 60
 */
EditableSettings.prototype['lnbits_watchdog_interval'] = 60;

/**
 * @member {Number} lnbits_watchdog_delta
 * @default 1000000
 */
EditableSettings.prototype['lnbits_watchdog_delta'] = 1000000;

/**
 * @member {String} lnbits_status_manifest
 * @default 'https://raw.githubusercontent.com/lnbits/lnbits-status/main/manifest.json'
 */
EditableSettings.prototype['lnbits_status_manifest'] = 'https://raw.githubusercontent.com/lnbits/lnbits-status/main/manifest.json';

/**
 * @member {String} lnbits_baseurl
 * @default 'http://127.0.0.1:5000/'
 */
EditableSettings.prototype['lnbits_baseurl'] = 'http://127.0.0.1:5000/';

/**
 * @member {Number} lnbits_reserve_fee_min
 * @default 2000
 */
EditableSettings.prototype['lnbits_reserve_fee_min'] = 2000;

/**
 * @member {Number} lnbits_reserve_fee_percent
 * @default 1.0
 */
EditableSettings.prototype['lnbits_reserve_fee_percent'] = 1.0;

/**
 * @member {Number} lnbits_service_fee
 * @default 0
 */
EditableSettings.prototype['lnbits_service_fee'] = 0;

/**
 * @member {Boolean} lnbits_hide_api
 * @default false
 */
EditableSettings.prototype['lnbits_hide_api'] = false;

/**
 * @member {String} lnbits_denomination
 * @default 'sats'
 */
EditableSettings.prototype['lnbits_denomination'] = 'sats';

/**
 * @member {String} lnbits_site_title
 * @default 'LNbits'
 */
EditableSettings.prototype['lnbits_site_title'] = 'LNbits';

/**
 * @member {String} lnbits_site_tagline
 * @default 'free and open-source lightning wallet'
 */
EditableSettings.prototype['lnbits_site_tagline'] = 'free and open-source lightning wallet';

/**
 * @member {String} lnbits_site_description
 */
EditableSettings.prototype['lnbits_site_description'] = undefined;

/**
 * @member {String} lnbits_default_wallet_name
 * @default 'LNbits wallet'
 */
EditableSettings.prototype['lnbits_default_wallet_name'] = 'LNbits wallet';

/**
 * @member {Array.<String>} lnbits_theme_options
 */
EditableSettings.prototype['lnbits_theme_options'] = undefined;

/**
 * @member {String} lnbits_custom_logo
 */
EditableSettings.prototype['lnbits_custom_logo'] = undefined;

/**
 * @member {String} lnbits_ad_space_title
 * @default 'Supported by'
 */
EditableSettings.prototype['lnbits_ad_space_title'] = 'Supported by';

/**
 * @member {String} lnbits_ad_space
 * @default 'https://shop.lnbits.com/;/static/images/lnbits-shop-light.png;/static/images/lnbits-shop-dark.png'
 */
EditableSettings.prototype['lnbits_ad_space'] = 'https://shop.lnbits.com/;/static/images/lnbits-shop-light.png;/static/images/lnbits-shop-dark.png';

/**
 * @member {Boolean} lnbits_ad_space_enabled
 * @default false
 */
EditableSettings.prototype['lnbits_ad_space_enabled'] = false;

/**
 * @member {Array.<String>} lnbits_allowed_currencies
 */
EditableSettings.prototype['lnbits_allowed_currencies'] = undefined;

/**
 * @member {Array.<String>} lnbits_admin_extensions
 */
EditableSettings.prototype['lnbits_admin_extensions'] = undefined;

/**
 * @member {Array.<String>} lnbits_extensions_manifests
 */
EditableSettings.prototype['lnbits_extensions_manifests'] = undefined;

/**
 * @member {Array.<String>} lnbits_admin_users
 */
EditableSettings.prototype['lnbits_admin_users'] = undefined;

/**
 * @member {Array.<String>} lnbits_allowed_users
 */
EditableSettings.prototype['lnbits_allowed_users'] = undefined;






export default EditableSettings;

