/**
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Lnbits);
  }
}(this, function(expect, Lnbits) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Lnbits.CreateExtension();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateExtension', function() {
    it('should create an instance of CreateExtension', function() {
      // uncomment below and update the code to test CreateExtension
      //var instance = new Lnbits.CreateExtension();
      //expect(instance).to.be.a(Lnbits.CreateExtension);
    });

    it('should have the property extId (base name: "ext_id")', function() {
      // uncomment below and update the code to test the property extId
      //var instance = new Lnbits.CreateExtension();
      //expect(instance).to.be();
    });

    it('should have the property archive (base name: "archive")', function() {
      // uncomment below and update the code to test the property archive
      //var instance = new Lnbits.CreateExtension();
      //expect(instance).to.be();
    });

    it('should have the property sourceRepo (base name: "source_repo")', function() {
      // uncomment below and update the code to test the property sourceRepo
      //var instance = new Lnbits.CreateExtension();
      //expect(instance).to.be();
    });

  });

}));
