/**
 * lnbits
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Lnbits);
  }
}(this, function(expect, Lnbits) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Lnbits.EditableSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EditableSettings', function() {
    it('should create an instance of EditableSettings', function() {
      // uncomment below and update the code to test EditableSettings
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be.a(Lnbits.EditableSettings);
    });

    it('should have the property lightningInvoiceExpiry (base name: "lightning_invoice_expiry")', function() {
      // uncomment below and update the code to test the property lightningInvoiceExpiry
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property boltzNetwork (base name: "boltz_network")', function() {
      // uncomment below and update the code to test the property boltzNetwork
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property boltzUrl (base name: "boltz_url")', function() {
      // uncomment below and update the code to test the property boltzUrl
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property boltzMempoolSpaceUrl (base name: "boltz_mempool_space_url")', function() {
      // uncomment below and update the code to test the property boltzMempoolSpaceUrl
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property boltzMempoolSpaceUrlWs (base name: "boltz_mempool_space_url_ws")', function() {
      // uncomment below and update the code to test the property boltzMempoolSpaceUrlWs
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lntipsApiEndpoint (base name: "lntips_api_endpoint")', function() {
      // uncomment below and update the code to test the property lntipsApiEndpoint
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lntipsApiKey (base name: "lntips_api_key")', function() {
      // uncomment below and update the code to test the property lntipsApiKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lntipsAdminKey (base name: "lntips_admin_key")', function() {
      // uncomment below and update the code to test the property lntipsAdminKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lntipsInvoiceKey (base name: "lntips_invoice_key")', function() {
      // uncomment below and update the code to test the property lntipsInvoiceKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property sparkUrl (base name: "spark_url")', function() {
      // uncomment below and update the code to test the property sparkUrl
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property sparkToken (base name: "spark_token")', function() {
      // uncomment below and update the code to test the property sparkToken
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property opennodeApiEndpoint (base name: "opennode_api_endpoint")', function() {
      // uncomment below and update the code to test the property opennodeApiEndpoint
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property opennodeKey (base name: "opennode_key")', function() {
      // uncomment below and update the code to test the property opennodeKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property opennodeAdminKey (base name: "opennode_admin_key")', function() {
      // uncomment below and update the code to test the property opennodeAdminKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property opennodeInvoiceKey (base name: "opennode_invoice_key")', function() {
      // uncomment below and update the code to test the property opennodeInvoiceKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnpayApiEndpoint (base name: "lnpay_api_endpoint")', function() {
      // uncomment below and update the code to test the property lnpayApiEndpoint
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnpayApiKey (base name: "lnpay_api_key")', function() {
      // uncomment below and update the code to test the property lnpayApiKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnpayWalletKey (base name: "lnpay_wallet_key")', function() {
      // uncomment below and update the code to test the property lnpayWalletKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnpayAdminKey (base name: "lnpay_admin_key")', function() {
      // uncomment below and update the code to test the property lnpayAdminKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndGrpcEndpoint (base name: "lnd_grpc_endpoint")', function() {
      // uncomment below and update the code to test the property lndGrpcEndpoint
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndGrpcCert (base name: "lnd_grpc_cert")', function() {
      // uncomment below and update the code to test the property lndGrpcCert
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndGrpcPort (base name: "lnd_grpc_port")', function() {
      // uncomment below and update the code to test the property lndGrpcPort
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndGrpcAdminMacaroon (base name: "lnd_grpc_admin_macaroon")', function() {
      // uncomment below and update the code to test the property lndGrpcAdminMacaroon
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndGrpcInvoiceMacaroon (base name: "lnd_grpc_invoice_macaroon")', function() {
      // uncomment below and update the code to test the property lndGrpcInvoiceMacaroon
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndGrpcMacaroon (base name: "lnd_grpc_macaroon")', function() {
      // uncomment below and update the code to test the property lndGrpcMacaroon
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndGrpcMacaroonEncrypted (base name: "lnd_grpc_macaroon_encrypted")', function() {
      // uncomment below and update the code to test the property lndGrpcMacaroonEncrypted
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndRestEndpoint (base name: "lnd_rest_endpoint")', function() {
      // uncomment below and update the code to test the property lndRestEndpoint
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndRestCert (base name: "lnd_rest_cert")', function() {
      // uncomment below and update the code to test the property lndRestCert
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndRestMacaroon (base name: "lnd_rest_macaroon")', function() {
      // uncomment below and update the code to test the property lndRestMacaroon
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndRestMacaroonEncrypted (base name: "lnd_rest_macaroon_encrypted")', function() {
      // uncomment below and update the code to test the property lndRestMacaroonEncrypted
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndCert (base name: "lnd_cert")', function() {
      // uncomment below and update the code to test the property lndCert
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndAdminMacaroon (base name: "lnd_admin_macaroon")', function() {
      // uncomment below and update the code to test the property lndAdminMacaroon
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndInvoiceMacaroon (base name: "lnd_invoice_macaroon")', function() {
      // uncomment below and update the code to test the property lndInvoiceMacaroon
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndRestAdminMacaroon (base name: "lnd_rest_admin_macaroon")', function() {
      // uncomment below and update the code to test the property lndRestAdminMacaroon
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lndRestInvoiceMacaroon (base name: "lnd_rest_invoice_macaroon")', function() {
      // uncomment below and update the code to test the property lndRestInvoiceMacaroon
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property eclairUrl (base name: "eclair_url")', function() {
      // uncomment below and update the code to test the property eclairUrl
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property eclairPass (base name: "eclair_pass")', function() {
      // uncomment below and update the code to test the property eclairPass
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property corelightningRpc (base name: "corelightning_rpc")', function() {
      // uncomment below and update the code to test the property corelightningRpc
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property clightningRpc (base name: "clightning_rpc")', function() {
      // uncomment below and update the code to test the property clightningRpc
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property clicheEndpoint (base name: "cliche_endpoint")', function() {
      // uncomment below and update the code to test the property clicheEndpoint
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsEndpoint (base name: "lnbits_endpoint")', function() {
      // uncomment below and update the code to test the property lnbitsEndpoint
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsKey (base name: "lnbits_key")', function() {
      // uncomment below and update the code to test the property lnbitsKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAdminKey (base name: "lnbits_admin_key")', function() {
      // uncomment below and update the code to test the property lnbitsAdminKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsInvoiceKey (base name: "lnbits_invoice_key")', function() {
      // uncomment below and update the code to test the property lnbitsInvoiceKey
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property fakeWalletSecret (base name: "fake_wallet_secret")', function() {
      // uncomment below and update the code to test the property fakeWalletSecret
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsBackendWalletClass (base name: "lnbits_backend_wallet_class")', function() {
      // uncomment below and update the code to test the property lnbitsBackendWalletClass
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsRateLimitNo (base name: "lnbits_rate_limit_no")', function() {
      // uncomment below and update the code to test the property lnbitsRateLimitNo
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsRateLimitUnit (base name: "lnbits_rate_limit_unit")', function() {
      // uncomment below and update the code to test the property lnbitsRateLimitUnit
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAllowedIps (base name: "lnbits_allowed_ips")', function() {
      // uncomment below and update the code to test the property lnbitsAllowedIps
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsBlockedIps (base name: "lnbits_blocked_ips")', function() {
      // uncomment below and update the code to test the property lnbitsBlockedIps
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsNotifications (base name: "lnbits_notifications")', function() {
      // uncomment below and update the code to test the property lnbitsNotifications
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsKillswitch (base name: "lnbits_killswitch")', function() {
      // uncomment below and update the code to test the property lnbitsKillswitch
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsKillswitchInterval (base name: "lnbits_killswitch_interval")', function() {
      // uncomment below and update the code to test the property lnbitsKillswitchInterval
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsWatchdog (base name: "lnbits_watchdog")', function() {
      // uncomment below and update the code to test the property lnbitsWatchdog
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsWatchdogInterval (base name: "lnbits_watchdog_interval")', function() {
      // uncomment below and update the code to test the property lnbitsWatchdogInterval
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsWatchdogDelta (base name: "lnbits_watchdog_delta")', function() {
      // uncomment below and update the code to test the property lnbitsWatchdogDelta
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsStatusManifest (base name: "lnbits_status_manifest")', function() {
      // uncomment below and update the code to test the property lnbitsStatusManifest
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsBaseurl (base name: "lnbits_baseurl")', function() {
      // uncomment below and update the code to test the property lnbitsBaseurl
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsReserveFeeMin (base name: "lnbits_reserve_fee_min")', function() {
      // uncomment below and update the code to test the property lnbitsReserveFeeMin
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsReserveFeePercent (base name: "lnbits_reserve_fee_percent")', function() {
      // uncomment below and update the code to test the property lnbitsReserveFeePercent
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsServiceFee (base name: "lnbits_service_fee")', function() {
      // uncomment below and update the code to test the property lnbitsServiceFee
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsHideApi (base name: "lnbits_hide_api")', function() {
      // uncomment below and update the code to test the property lnbitsHideApi
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsDenomination (base name: "lnbits_denomination")', function() {
      // uncomment below and update the code to test the property lnbitsDenomination
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsSiteTitle (base name: "lnbits_site_title")', function() {
      // uncomment below and update the code to test the property lnbitsSiteTitle
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsSiteTagline (base name: "lnbits_site_tagline")', function() {
      // uncomment below and update the code to test the property lnbitsSiteTagline
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsSiteDescription (base name: "lnbits_site_description")', function() {
      // uncomment below and update the code to test the property lnbitsSiteDescription
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsDefaultWalletName (base name: "lnbits_default_wallet_name")', function() {
      // uncomment below and update the code to test the property lnbitsDefaultWalletName
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsThemeOptions (base name: "lnbits_theme_options")', function() {
      // uncomment below and update the code to test the property lnbitsThemeOptions
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsCustomLogo (base name: "lnbits_custom_logo")', function() {
      // uncomment below and update the code to test the property lnbitsCustomLogo
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAdSpaceTitle (base name: "lnbits_ad_space_title")', function() {
      // uncomment below and update the code to test the property lnbitsAdSpaceTitle
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAdSpace (base name: "lnbits_ad_space")', function() {
      // uncomment below and update the code to test the property lnbitsAdSpace
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAdSpaceEnabled (base name: "lnbits_ad_space_enabled")', function() {
      // uncomment below and update the code to test the property lnbitsAdSpaceEnabled
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAllowedCurrencies (base name: "lnbits_allowed_currencies")', function() {
      // uncomment below and update the code to test the property lnbitsAllowedCurrencies
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAdminExtensions (base name: "lnbits_admin_extensions")', function() {
      // uncomment below and update the code to test the property lnbitsAdminExtensions
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsExtensionsManifests (base name: "lnbits_extensions_manifests")', function() {
      // uncomment below and update the code to test the property lnbitsExtensionsManifests
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAdminUsers (base name: "lnbits_admin_users")', function() {
      // uncomment below and update the code to test the property lnbitsAdminUsers
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

    it('should have the property lnbitsAllowedUsers (base name: "lnbits_allowed_users")', function() {
      // uncomment below and update the code to test the property lnbitsAllowedUsers
      //var instance = new Lnbits.EditableSettings();
      //expect(instance).to.be();
    });

  });

}));
